# Generated by Django 3.2.6 on 2021-09-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('bio', models.TextField()),
                ('avatar_url', models.TextField()),
                ('fan_num', models.CharField(max_length=10)),
                ('subs_num', models.CharField(max_length=10, verbose_name='Subscription count')),
                ('videos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('cover_url', models.TextField()),
                ('plays', models.CharField(max_length=10)),
                ('shoots', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('likes', models.CharField(max_length=10)),
                ('coins', models.CharField(max_length=10)),
                ('stars', models.CharField(max_length=10)),
                ('author_id', models.CharField(max_length=12)),
                ('comments', models.TextField()),
            ],
        ),
    ]
